name: Auto ZIP & Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # STEP 1: Extract version from tag (e.g. v0.0.2)
      - name: Extract version from tag
        id: tag
        run: |
          TAG=${GITHUB_REF##*/}
          VERSION="${TAG#v}"
          echo "VERSION=$VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      # STEP 2: Debug - List files/folders
      - name: List root directory contents
        run: ls -la

      # STEP 3: Zip the folder (change `all-export` if needed)
      - name: Zip the folder
        run: |
          VERSION=${{ steps.tag.outputs.VERSION }}
          ZIP_NAME="all-export_${VERSION}.zip"
          
          if [ -d "all-export" ]; then
            zip -r "$ZIP_NAME" all-export
            echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV
          else
            echo "❌ Folder 'all-export' not found!"
            exit 1
          fi

      # STEP 4: Debug - Show created ZIP
      - name: Show created ZIP file
        run: ls -la *.zip || echo "❌ ZIP not created"

      # STEP 5: Upload ZIP to GitHub release
      - name: Upload ZIP to release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.ZIP_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
