name: Auto ZIP & Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get tag version (e.g., v0.0.2)
        id: tag
        run: |
          TAG=${GITHUB_REF##*/}
          echo "VERSION=${TAG#v}" >> $GITHUB_OUTPUT

      - name: Zip the folder
        run: |
          VERSION=${{ steps.tag.outputs.VERSION }}
          ZIP_NAME="wp-all-export_${VERSION}.zip"
          zip -r "$ZIP_NAME" all-export
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV

      - name: Upload ZIP to release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.ZIP_NAME }}
